### ISSUE TITLE
Moving to LGPL

### ISSUE THREAD

**Issue by fabsx00** [octopus-platform/joern#101]
I have split off a program analysis library from joern called `jpanlib`, and I would like to make that library available under the LGPL, so that people writing code that use the library can use any license they want.

To be on the safe side, I'd like to ask everyone who has contributed a fix to joern at some point whether they are OK with this. I've gone through the logs, this should be: @ideadapt @l4l and @yangke

Please let me know if this is OK with you guys.

**Comment by l4l** [comment]
Sure

**Comment by ideadapt** [comment]
Hi fab, thats ok for me!

**Comment by yangke** [comment]
Sure and absolutely
