### ISSUE TITLE
Compatibility issue with pyneo 3 

### ISSUE THREAD

**Issue by AntoineHus** [octopus-platform/joern#105]
Hello, 

I tried to install Joern on my linux pc and I had an issue with pyneo, I discovered that the version installed was the 3b2 from the python repository.

So, I reverse installed the version 2 and Joern worked. 

We need to update the documentation about that or the joern source code for installing pyneo2 or updating it for being compatible with pyneo3.

Thanks.

**Comment by fabsx00** [comment]
The new version of joern currently in the `dev` branch no longer uses neo4j. We should release soon and not care about py2neo anymore ;)
