### ISSUE TITLE
[dev] Bug: Escaping for OrientDB wget parameters missing

### ISSUE THREAD

**Issue by evonide** [octopus-platform/joern#113]
A fresh copy of joern/dev can't be build with "./build.sh".
Following messages appear:
```
$ ./build.sh 
:compileJava UP-TO-DATE
[...]
Download OrientDB with wget.
Download OrientDB ...

:projects:octopus:octopus-server:downloadAndExtractOrientDB FAILED

FAILURE: Build failed with an exception.
```

Executing the wget command from "joern/projects/octopus/octopus-server/build.gradle" manually like:
```
wget http://orientdb.com/download.php?file=orientdb-community-2.1.5.tar.gz&os=multi -O test
```
will create a "download.php?file=orientdb-community-2.1.5.tar.gz" file.

A suggested fix would require the escaping of the url and $ARCHIVE_FILENAME as the filepath can contain spaces, too. However, I couldn't get this fix running:
```
println "wget \"http://orientdb.com/download.php?file=orientdb-community-2.1.5.tar.gz&os=multi\" -O \"$ARCHIVE_FILENAME\"".execute().text
```

**Comment by fabsx00** [comment]
Closing, because we've removed orientdb completely from dev.
