### ISSUE TITLE
Joern only finds certain types of function calls

### ISSUE THREAD

**Issue by tophertimzen** [octopus-platform/joern#115]
It appears as if Joern only finds functions that look like the following

`StrSize (Buffer)`

as opposed to

`StrSize(Buffer).`

The necessity for the space between the name and open parentheses prevents me from using joern on large code bases. 

Example below

```bash
vagrant@vagrant-ubuntu-trusty-64:~/queries$ echo "getCallsTo('*Str*').code" | joern-lookup -g | egrep '[a-zA-Z0-9] \('

StrSize ( FileName )

StrSize ( OldInfo -> FileName )

StrSize ( OldInfo -> FullName )
```

But when redefined as "StrSize(" I find nothing

```bash
vagrant@vagrant-ubuntu-trusty-64:~/queries$ echo "getCallsTo('*Str*').code" | joern-lookup -g | egrep '[a-zA-Z0-9]\('

vagrant@vagrant-ubuntu-trusty-64:~/queries$
```

It would be great if when joern parses a "c" file it picks up both implementations of performing a function call.

**Comment by fabsx00** [comment]
What branch are you using? It certainly isn't the parser that's causing this, it must be something with getCallsTo. Have you tried `.*Str.*`, I'm not sure whether this might be a regular expression that `getCallsTo` is expecting. Also try `queryNodeIndex('type:Call*').filter{ it.code.startsWith("Str") }`

**Comment by tophertimzen** [comment]
I've been using master. And yeah that query does the same thing and doesn't find functions without the space in the invocation.

**Comment by fabsx00** [comment]
Ah, ok, I just checked it, here's the thing: the parser correctly identifies calls even if they do not contain the space, e.g. `foo()` is recognized as a call. However, the `code` attribute is normalized and set to `foo ()`, including the space. So, in other words, regardless of whether the original code contained a space or not, in joern's nodes, the space will be present.

**Comment by fabsx00** [comment]
You could do a `queryNodeIndex('type:Callee').filter{ it.name.startsWith(...) }` btw, then whether there is a space or not does not matter.
