### ISSUE TITLE
Neo4j 2.1.8

### ISSUE THREAD

**Issue by flip111** [octopus-platform/joern#116]
The [manual](https://joern.readthedocs.io/en/latest/installation.html) states: `To install the neo4j server, download version 2.1.8 from http://www.neo4j.com/download/other-releases.`

However i don't see that version on this page, would it be ok to use the latest version of neo4j ?

**Comment by fabsx00** [comment]
You can just edit the download URL to
https://neo4j.com/download-thanks/?edition=community&flavour=unix&release=2.1.8

**Comment by flip111** [comment]
Thanks. Any reasons why this specific version and not the latest version? Would be nicer to use the latest version.

**Comment by fabsx00** [comment]
Things in neo4j change rapidly. I would expect the existing code to work with neo4j 2.X, but not necessarily with 3.X. It simply has not been tested.
