### ISSUE TITLE
new josh connection hangs when python has connected earlier

### ISSUE THREAD

**Issue by timhemel** [octopus-platform/joern#120]
Tested on the dev-branch, commit f59279852be62e1a2bf4ceac2577aa4d71be0c55:

1 Start joern-server.sh with a loaded project (testCode.tar.gz).

2 connect with makeconn.py:
```
#!/usr/bin/env python3

from octopus.server.DBInterface import DBInterface

projectName = 'testCode.tar.gz'
query = """g.V(65632)"""

db = DBInterface()
# db.disable_json()
db.connectToDatabase(projectName)

result = db.runGremlinQuery(query)
for x in result:
    print(x)
```
3 a result is returned:
```
$ ./testconn.py 
{'label': 'vertex', 'type': 'vertex', 'id': 65632, 'properties': {'_key': '143', 'childNum': '', 'code': 'slicing1', 'functionId': '', 'type': 'Function', 'isCFGNode': '', 'location': '38:0:512:624'}}
```
4 List the josh shells:
```
$ josh ls
6000 testCode.tar.gz .python_testCode.tar.gz_0 free
```
5 Create a new josh shell:
```
$ josh cr testCode.tar.gz
```
6 Connect to the shell:
```
$ josh -p 6001 co
```
This takes forever. The shell is occupied, as shown by `josh ls`:
```
$ josh ls
6000 testCode.tar.gz .python_testCode.tar.gz_0 free
6001 testCode.tar.gz noname occupied
```

**Comment by fabsx00** [comment]
We're cleaning up and testing the shell-code right now. Hopefully, this will be resolved tonight. Thanks for reporting.

**Comment by fabsx00** [comment]
Hi Tim,
we did a lot of work on Octopus today, which I have just pulled into Joern. In particular, this introduces changes to the shell. Please let me know if this issue still exists.

**Comment by timhemel** [comment]
Hi Fabs,

Just merged the latest dev branch and the issue is still there.

**Comment by timhemel** [comment]
Tested it again and discovered that there is a `-q` option with the connect command. If I use that, things work. The `-p` option does not. What is the difference between the options?

**Comment by a0x77n** [comment]
Option `-p` is used to set the port of the REST server. Option `-q` is used to specify the port of the shell (i.e. the port number returned by `josh list`.

One more thing: We moved the shell to octopus-tools where it is named `octopus-shell`. I just forgot to delete `josh`. So please use `octopus-shell`. Old `josh` will be deleted soon.
