### ISSUE TITLE
Joern build fails

### ISSUE THREAD

**Issue by pienginering** [octopus-platform/joern#146]
Hi,

I have followed the steps provided here: http://joern.readthedocs.io/en/latest/installation.html . 
However, when executing "./build.sh" it fails with the following errors (java 8 and gradle 2.x is intalled):

`
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:check
:projects:compileJava UP-TO-DATE
:projects:processResources UP-TO-DATE
:projects:classes UP-TO-DATE
:projects:jar UP-TO-DATE
:projects:assemble UP-TO-DATE
:projects:check
:projects:build
:projects:extensions:compileJava UP-TO-DATE
:projects:extensions:processResources UP-TO-DATE
:projects:extensions:classes UP-TO-DATE
:projects:extensions:jar UP-TO-DATE
:projects:extensions:assemble UP-TO-DATE
:projects:extensions:check
:projects:extensions:build
:projects:languages:compileJava UP-TO-DATE
:projects:languages:processResources UP-TO-DATE
:projects:languages:classes UP-TO-DATE
:projects:languages:jar UP-TO-DATE
:projects:languages:assemble UP-TO-DATE
:projects:languages:check
:projects:languages:build
:projects:octopus:compileJava/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:42: error: ')' expected
		post("executeplugin/", (req, res) -> {
		                           ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:42: error: illegal start of expression
		post("executeplugin/", (req, res) -> {
		                                   ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:42: error: illegal start of expression
		post("executeplugin/", (req, res) -> {
		                                     ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:43: error: illegal start of type
			return new ExecutePluginHandler().handle(req, res); });
			                                                     ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: invalid method declaration; return type required
		get("manageprojects/create/:projectName", (req, res) -> {
		^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: illegal start of type
		get("manageprojects/create/:projectName", (req, res) -> {
		    ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: illegal start of type
		get("manageprojects/create/:projectName", (req, res) -> {
		                                          ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: ')' expected
		get("manageprojects/create/:projectName", (req, res) -> {
		                                           ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: ';' expected
		get("manageprojects/create/:projectName", (req, res) -> {
		                                              ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: <identifier> expected
		get("manageprojects/create/:projectName", (req, res) -> {
		                                                   ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: illegal start of type
		get("manageprojects/create/:projectName", (req, res) -> {
		                                                     ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: <identifier> expected
		get("manageprojects/create/:projectName", (req, res) -> {
		                                                      ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:45: error: ';' expected
		get("manageprojects/create/:projectName", (req, res) -> {
		                                                       ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: illegal start of type
			return new CreateProjectHandler().handle(req, res);
			^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: <identifier> expected
			return new CreateProjectHandler().handle(req, res);
			      ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: ';' expected
			return new CreateProjectHandler().handle(req, res);
			          ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: illegal start of type
			return new CreateProjectHandler().handle(req, res);
			                               ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: <identifier> expected
			return new CreateProjectHandler().handle(req, res);
			                                ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: ';' expected
			return new CreateProjectHandler().handle(req, res);
			                                 ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: invalid method declaration; return type required
			return new CreateProjectHandler().handle(req, res);
			                                  ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: <identifier> expected
			return new CreateProjectHandler().handle(req, res);
			                                            ^
/root/static_analysis/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: <identifier> expected
			return new CreateProjectHandler().handle(req, res);
`

am I am the only one facing that errors?

Thanks.
Mario

**Comment by fabsx00** [comment]
hm. I just cloned, then started ./build.sh, and it seems to work fine. Can you try to do a fresh clone? We merged a lot of commits today.

**Comment by pienginering** [comment]
hi fabian. A fresh clone worked - thanks.
