### ISSUE TITLE
Failing tests when building joern 

### ISSUE THREAD

**Issue by rmmilewi** [octopus-platform/joern#148]
Hello! I'm a compilers/infrastructure person who is interested in taming several million lines of C++. My conventional, heavyweight compiler infrastructure struggles to handle the extremely complex code, and I was enchanted by the idea of using a fuzzy parser for C++. Joern seems to be exactly what I need.

Unfortunately, when I try to build joern with grade, I get several failing tests:

```
:projects:extensions:joern-fuzzyc:test
tests.argumentTainter.TestArgumentTainter > testDefUseCFGPatcher FAILED
    java.util.NoSuchElementException at TestArgumentTainter.java:65
tests.ddg.testDDGCreator > simplestTest FAILED
    java.util.NoSuchElementException at testDDGCreator.java:33
tests.ddg.testDDGCreator > testConverter FAILED
    java.util.NoSuchElementException at testDDGCreator.java:55
```

The TestArgumentTainter test attempts to call next() on an IndexHits object after doing a lookup of functions by name, and this triggers the NoSuchElementException. 

I'm currently trying to build joern on Mac OSx (El Capitan, 10.11.6) with Java 8. For the sake of full disclosure, I did have to make one small change to get joern to build, which was to add "-prefix=" when calling python3 because otherwise I got this error: 

`error: can't combine user with with prefix/exec_prefix/home or install_(plat)base`

That seems to be due to a weird configuration issue as noted [here](http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install). However, I cannot say whether that was in any way connected to the test failure issue that I am seeing.

**Comment by vlad902** [comment]
This is because of how OS X has installed python by default. This fixes it:
```
diff --git a/build.gradle b/build.gradle
index 74ff2a4..3211a21 100644
--- a/build.gradle
+++ b/build.gradle
@@ -24,7 +24,7 @@ allprojects {

 task joernTools(type: Exec) {
     workingDir './python/joern-tools'
-    commandLine 'python3', 'setup.py', 'install', '--user'
+    commandLine 'python3', 'setup.py', 'install'
 }

 // Copy extensions and plugins into Octopus plugin directory
diff --git a/projects/octopus/build.gradle b/projects/octopus/build.gradle
index 73949ff..cb92c2e 100644
--- a/projects/octopus/build.gradle
+++ b/projects/octopus/build.gradle
@@ -46,12 +46,12 @@ dependencies{

 task octopusMlutils(type: Exec) {
     workingDir './python/octopus-mlutils'
-    commandLine 'python3', 'setup.py', 'install', '--user'
+    commandLine 'python3', 'setup.py', 'install'
 }

 task octopusTools(type: Exec, dependsOn: octopusMlutils) {
     workingDir './python/octopus-tools'
-    commandLine 'python3', 'setup.py', 'install', '--user'
+    commandLine 'python3', 'setup.py', 'install'
 }

 task copyToLib(type: Copy) {
```

**Comment by rmmilewi** [comment]
Thanks for that! That definitely fixes the python issue. Unfortunately, I still have the failed tests, so they must be an independent issue.

**Comment by vlad902** [comment]
It is, I pressed comment too quickly and went back and edited the reply. The failed tests you're experiencing are an unfortunately expected at this time and can be ignored.

**Comment by rmmilewi** [comment]
Yes! Problem fixed. Everything builds fine when running build.sh. Thank you for your assistance!
