### ISSUE TITLE
missing antlr4-4.2.1-SNAPSHOT-complete.jar for the genParser.sh

### ISSUE THREAD

**Issue by gengyifeng** [octopus-platform/joern#31]
I'm trying to improve the lexer and parser rules. There should be antlr4-4.2.1-SNAPSHOT-complete.jar for the genParser.sh, but it is missing. Where can I get this jar?

**Comment by pgh15** [comment]
I'd like to make a small change to the parser and have tried to follow the above instructions without any luck. The current version of antlr4 doesn't build with maven but has it's own python build script which didn't work. So I downloaded the precompiled jars and tried all of them in place of  antlr4-4.2.1-SNAPSHOT-complete.jar hoping that at least antlr-4.2.2-complete.jar would be compatible. Without making any changes to any g4 file, genparsers.sh produces something that no longer builds successfully with ant. Is there any chance I can get a pre-built antlr4-4.2.1-SNAPSHOT-complete.jar from somewhere that definitely works?

Thanks,
Paul

**Comment by fabsx00** [comment]
Hi Paul,
here you go: http://mlsec.org/joern/lib/antlr4-4.2.1-SNAPSHOT-complete.jar
Hope this helps.
Fabian

**Comment by pgh15** [comment]
Hi Fabian,
Perfect. Thanks.

Paul
